package ma.ac.esi.nutritrack.model;

public class Ingredient {
    private int id;
    private String name;
    private int calories;

    // Existing constructor
    public Ingredient(int id, String name, int calories) {
        this.id = id;
        this.name = name;
        this.calories = calories;
    }

    // Overloaded constructor (without id)
    public Ingredient(String name, int calories) {
        // Set id to a default value (like 0) until it is generated by the DB.
        this.id = 0;
        this.name = name;
        this.calories = calories;
    }

    // Getters and Setters
    public int getId() {
        return id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public int getCalories() {
        return calories;
    }
    
    public void setCalories(int calories) {
        this.calories = calories;
    }
}
